<?php
$idEstado=$_GET['estado'];
$codigo=$_GET['codigo'];
if($idEstado==3){
    header("location:../reporte/reporte.php?codigo=".$codigo);
}else{
    header("location:despacho.php?codigo=".$codigo);
}
?>